# GitHub Actions workflow for rendering the Quarto document and creating a release

name: Render Quarto Document and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nix environment
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          log-directives: nix_installer=trace

      - name: Cache Nix dependencies
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Nix environment
        run: nix-build

      - name: Render book with Quarto
        run: nix-shell --run "quarto render"
        
      - name: Convert PDF to DJVU
        run: nix-shell --run "pdf2djvu _book/Book-Title.pdf -o _book/Book-Title.djvu"
        

      - name: Create GitHub Release with artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "_book/*.pdf,_book/*.epub,_book/*.docx,_book/*.djvu,*.tex"
          bodyFile: "other/release.md"
          